[notebook]
dir = "~/Documents/notasys"

[note]
filename = "{{slug title}}"
template = "default.md"

[tool]
editor = "nvim"

[alias]
n = 'zk new --template="default.md"'
d = 'zk new --template="daily.md"'
t = 'zk list 1_temp'

[filter]
temp = "--sort created 1_temp"


# journal group
[group.journal]
paths = ["daybyday"]
